Remove the use of DynamoTestUtil.clearTable() on critical health code tables.
Sage-Bionetworks/BridgePF pull request #1359
Opened 2017-01-27 23:29 UTC by alxdarksage

While testing notifications, I discovered my account's healthCode was changing in the local environment. After verifying this has not happened in production, and tracking down why it occurs, it comes down to the fact we're deleting records from the key mapping table, HealthCode.

This would be catastrophic if it happened in any other environment. I don't know how these tests would run anywhere else, but I'm removing the user of this method so it doesn't happen locally.

2017-01-28 02:37 UTC, DwayneJengSage commented
It looks like the only remaining place this is being used is DynamoBackfillDaoTest. How difficult would it be to remove it from there as well, and then delete clearTables() so we can be sure no one is using it?

2017-01-28 02:40 UTC, DwayneJengSage commented
Other than that, change looks good.

2017-01-30 17:55 UTC, alxdarksage commented
Yeah let me remove the last use of clearTables() today, sounds good.

2017-01-30 19:28 UTC, alxdarksage commented
Okay, I changed that last test and removed the utility class that implements clearTable().

2017-01-31 05:42 UTC, DwayneJengSage requested changes
One minor change. Otherwise, looks good.

2017-01-31 05:42 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoBackfillDaoTest.java
> +import com.newrelic.agent.deps.com.google.common.collect.Lists;
Remove NewRelic from our imports. Is there any way we can permanently disable this library from showing up in our code?

2017-01-31 16:31 UTC, alxdarksage commented
I removed that import. I also found a type filter feature in Eclipse where I can add the new relic package that keeps getting imported (haven't used before but it worked when fixing this class).

2017-02-01 05:45 UTC, merged