Rename ScheduleContext.now to ScheduleContext.startsOn, which is more accurate.
Sage-Bionetworks/BridgePF pull request #1440
Opened 2017-05-10 16:59 UTC by alxdarksage

We're about to introduce a new endpoint (/v4/activities) that will allow the client to retrieve activities for an arbitrary date range. When we do this, the "now" value in the ScheduleContext will really be the "startsOn" value of the query, and only "now" by default in the v3 of the API. Just doing a rename here to separate this change from the functional changes that are coming.

2017-05-10 19:28 UTC, DwayneJengSage requested changes

2017-05-10 19:28 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/models/schedules/ScheduleContextTest.java
> +        assertEquals(now, context.getStartsOn());
Minor: This isn't a problem with the code per se, but your change did shine a spotlight on the fact that we didn't have any unit tests on withContext(). We should add that here. It's only 2 extra lines to this test.

Also, endsOn and startsOn are both set to potentially the same value. We should change the test so they use different values to make sure we aren't getting our wires crossed.

2017-05-10 19:28 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/play/controllers/ScheduledActivityController.java
> +                .withActivitiesAccessedOn(DateUtils.getCurrentDateTime().withZone(requestTimeZone))
We should update the unit tests to make sure we're saving the right time zone.

2017-05-10 20:14 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/models/schedules/ScheduleContextTest.java
> +        assertEquals(now, context.getStartsOn());
Updated to test the withContext() method. (This found an error when copying a context where accountCreatedOn is null).

2017-05-10 20:24 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/play/controllers/ScheduledActivityController.java
> +                .withActivitiesAccessedOn(DateUtils.getCurrentDateTime().withZone(requestTimeZone))
Added

2017-05-10 22:36 UTC, DwayneJengSage reviewed
2 minor test comments. I don't want to bloat this change request, but at the same time, we should have tests for all our code.

2017-05-10 22:36 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/models/schedules/ScheduleContext.java
> +            }
This change has uncovered 2 more test gaps. We don't have tests for:

* withContext() doesn't test accountCreatedOn. (I mean, we found out indirectly that it does, but if withContext() suddenly stopped copying accountCreatedOn, we'd have no way of detecting that.)
* withAccountCreatedOn() null case.

2017-05-11 00:15 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/models/schedules/ScheduleContext.java
> +            }
Okay, I created a method to test all values being set, and then set through the withContext method, and another method to test none of the values being set, and then that again being copied through the withContext method.

2017-05-11 16:55 UTC, liujoshua approved these changes

2017-05-11 17:45 UTC, merged