BRIDGE-1947: Upgrade aws java sdk clients
Sage-Bionetworks/BridgePF pull request #1564
Opened 2017-09-19 17:48 UTC by zaro0508

To provide visibility into DynamoDB usage new relic java agent requires
DyanoDB client >= 1.11.106.  This will upgrade the clients to the
latest version.

2017-09-19 18:00 UTC, alxdarksage requested changes
Have you run our "unit" tests and verified that everything works?

2017-09-20 00:10 UTC, zaro0508 commented
Ran unit tests on my local machine.  All passed except for one test failure "org.sagebionetworks.bridge.dynamodb.DynamoHealthDataDaoDdbTest".  I rebuilt and reran with existing libs and saw the exact same failure.  Below is the failure..

[error] Test org.sagebionetworks.bridge.dynamodb.DynamoHealthDataDaoDdbTest.getRecordsByHealthCodeCreatedOnSchemaId failed: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0, took 0.251 sec
[error]     at java.util.ArrayList.rangeCheck(ArrayList.java:653)
[error]     at java.util.ArrayList.get(ArrayList.java:429)
[error]     at org.sagebionetworks.bridge.dynamodb.DynamoHealthDataDaoDdbTest.getRecordsByHealthCodeCreatedOnSchemaId(DynamoHealthDataDaoDdbTest.java:132)
[error]     ...
[error] Test org.sagebionetworks.bridge.dynamodb.DynamoHealthDataDaoDdbTest.createdOnInRangeForgetRecordsByHealthCodeCreatedOnSchemaId failed: java.lang.AssertionError: Values should be different. Actual: 0, took 0.235 sec
[error]     at org.sagebionetworks.bridge.dynamodb.DynamoHealthDataDaoDdbTest.createdOnInRangeForgetRecordsByHealthCodeCreatedOnSchemaId(DynamoHealthDataDaoDdbTest.java:227)
[error]     ...
[error] Test org.sagebionetworks.bridge.dynamodb.DynamoHealthDataDaoDdbTest.getRecordsByHealthCodeCreatedOnSchemaIdWithLimit failed: java.lang.AssertionError: expected:<10> but was:<0>, took 2.158 sec
[error]     at org.sagebionetworks.bridge.dynamodb.DynamoHealthDataDaoDdbTest.getRecordsByHealthCodeCreatedOnSchemaIdWithLimit(DynamoHealthDataDaoDdbTest.java:182)
[error]     ...
[error] Failed: Total 7, Failed 3, Errors 0, Passed 4
[error] Failed tests:
[error] 	org.sagebionetworks.bridge.dynamodb.DynamoHealthDataDaoDdbTest
[error] (test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 45 s, completed Sep 19, 2017 4:25:05 PM

2017-09-20 00:16 UTC, DwayneJengSage commented
Works for me. Is there something wrong with your DynamoDB setup?

2017-09-22 00:06 UTC, zaro0508 commented
Alx fixed my dynamo tables.  I have rerun the unit test suite with new aws libs and all tests are passing now.

2017-09-22 00:09 UTC, alxdarksage approved these changes

2017-09-22 03:23 UTC, merged