Migrate participant options to accounts table
Sage-Bionetworks/BridgePF pull request #1656
Opened 2018-02-16 21:36 UTC by alxdarksage

Loading and saving an account will move the values in the participant options table to the accounts table. Separately from this, we will need to run a migration to move over the values. New accounts write to the account table.

This still requires more testing, but all existing/added unit and integration tests pass.

2018-02-28 08:33 UTC, DwayneJengSage requested changes

2018-02-28 08:33 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/dao/ParticipantOptionTest.java
>      public void canRetrieveEmptyValuesFromStudyParticipant() {
Nitpick: The test names for fromAccount and fromParticipant seem to be switched.

2018-02-28 08:33 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/dao/ParticipantOptionTest.java
> +        assertEquals("true", result);
We should test a non-default value for this test.

2018-02-28 08:33 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/ConsentService.java
> +        account = accountDao.getAccount(AccountId.forId(study.getIdentifier(), account.getId()));
Previously, we set the sharing scope and the consents separately because they came from different sources. Now that they're both in RDS, does this still need to be true?

If not, can we have the same accountDao.updateAccount() call be used to do both? accountDao.getAccount() already populates the account object with participant options, so all we need to do is account.setSharingScope(SharingScope.NO_SHARING).

2018-02-28 08:33 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/services/ParticipantOptionsServiceTest.java
> +        account.setNotifyByEmail(Boolean.TRUE);
Minor: Would it be better to consolidate all of these "get" tests into a single test so all of the test is in a single place?

2018-02-28 08:33 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/services/ParticipantOptionsServiceTest.java
> +        assertTrue(service.getOptions(TestConstants.TEST_STUDY, HEALTH_CODE).getBoolean(EMAIL_NOTIFICATIONS));
Would it be better to use a non-default value for the test?

2018-02-28 08:33 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/services/ParticipantOptionsServiceTest.java
> +        LinkedHashSet<String> langs = TestUtils.newLinkedHashSet("fr","en","kl");
For completeness, do we also want a test for getLinkedHashSet?

2018-02-28 08:33 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/ParticipantOptionsService.java
> +        return new ParticipantOptionsLookup(Maps.newHashMap());
Unit test for account not found?

2018-02-28 08:33 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/ParticipantOptionsService.java
> +        checkNotNull(option == ParticipantOption.EMAIL_NOTIFICATIONS);
I'm not sure this is the check you're looking for. option==ParticipantOption.EMAIL_NOTIFICATIONS will always be non-null. (Here and a few other places in this class.)

2018-02-28 08:33 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/ParticipantOptionsService.java
> +        }
If the account is not found, is that an error?

Also, unit tests for the account not found case? (Here and in several other places in this class.)

2018-02-28 20:07 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/dao/ParticipantOptionTest.java
>      public void canRetrieveEmptyValuesFromStudyParticipant() {
Swapped them

2018-02-28 20:07 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/dao/ParticipantOptionTest.java
> +        assertEquals("true", result);
changed to false

2018-02-28 20:09 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/services/ParticipantOptionsServiceTest.java
> +        account.setNotifyByEmail(Boolean.TRUE);
This service is going to go away in a subsequent check in, so I wouldn't invest effort in refactoring.

2018-02-28 20:10 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/ConsentService.java
> +        account = accountDao.getAccount(AccountId.forId(study.getIdentifier(), account.getId()));
Yes, we definitely want to do this. I am holding off to keep the size of this PR down, but a subsequent PR will remove the options service, and in most cases, that'll lead to consolidating calls to update the account.

2018-02-28 20:14 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/services/ParticipantOptionsServiceTest.java
> +        LinkedHashSet<String> langs = TestUtils.newLinkedHashSet("fr","en","kl");
added

2018-02-28 20:18 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/ParticipantOptionsService.java
> +        return new ParticipantOptionsLookup(Maps.newHashMap());
added

2018-02-28 20:20 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/ParticipantOptionsService.java
> +        checkNotNull(option == ParticipantOption.EMAIL_NOTIFICATIONS);
Yeow! changed to checkArgument.

2018-02-28 20:37 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/ParticipantOptionsService.java
> +        }
Now throws an exception, added unit tests for all the setter methods to verify.

2018-03-01 20:51 UTC, DwayneJengSage approved these changes

2018-03-01 20:57 UTC, merged