Better cache key management
Sage-Bionetworks/BridgePF pull request #1688
Opened 2018-04-06 22:28 UTC by alxdarksage

The cache key situation is pretty out of control. We're creating string keys all over the place with no centralization, and our oldest code uses a set of key classes that Eric created, that were difficult enough to use that we stopped using them. In addition, we're creating some keys that aren't namespaced at all. 

In all it's easier to keep a list of keys that should be kept out of the cache API (so that's implemented as per BRIDGE-2135).

On the downside, this touches a lot of code.

2018-04-13 23:59 UTC, DwayneJengSage requested changes

2018-04-13 23:59 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/cache/CacheKeys.java
> +    public final static boolean isPublic(String key) {
Unit test for isPublic()?

2018-04-13 23:59 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/cache/CacheKeys.java
> +    public final static class CacheKey {
Does this need to be an inner class? Would it be cleaner to have CacheKey be the outer class with a bunch of static util methods? (Or alternatively, split these two into two top-level classes?)

2018-04-13 23:59 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/cache/CacheKeys.java
> +    }
Unit test for reauthCacheKey?

2018-04-16 23:58 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/cache/CacheKeys.java
> +    public final static class CacheKey {
Reduced this to one class with static factory methods (CacheKey singular).

2018-04-16 23:58 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/cache/CacheKeys.java
> +    public final static boolean isPublic(String key) {
Added

2018-04-16 23:58 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/cache/CacheKeys.java
> +    }
Added

2018-04-18 05:49 UTC, DwayneJengSage approved these changes

2018-04-18 16:28 UTC, merged