An URL shortener service.
Sage-Bionetworks/BridgePF pull request #1700
Opened 2018-05-02 19:31 UTC by alxdarksage

Pretty simple, the service will generate an URL you can substitute for your original (probably very long) URL. The URL provided points back to BridgePF to resolve and redirect to the original URL. Service will not issue conflicting short URLs, and it will not generate a different URL for the same long URL if it hasn't expired. URLs do expire, and are not intended to be permanent (e.g. like bit.ly).

2018-05-02 22:58 UTC, DwayneJengSage requested changes
One minor comment about while loop vs do-while loop. Otherwise, looks fine.

2018-05-02 22:58 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/UrlShortenerService.java
> +        }
Minor: Would a do-while loop be better, so you don't have to repeat the code twice?

2018-05-02 23:48 UTC, alxdarksage commented
Changed to a do loop.

2018-05-03 00:30 UTC, DwayneJengSage approved these changes

2018-05-03 02:21 UTC, merged