Logical delete schemas
Sage-Bionetworks/BridgePF pull request #1751
Opened 2018-07-18 20:48 UTC by alxdarksage

2018-08-24 23:26 UTC, DwayneJengSage requested changes
Overall looks good, a few notes.

2018-08-24 23:26 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/models/upload/UploadSchemaTest.java
> +        assertTrue(jsonNode.get("deleted").booleanValue());
Should we also test that the POJO has deleted=true?

2018-08-24 23:26 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/play/controllers/UploadSchemaControllerTest.java
> +        verify(mockSvc).deleteUploadSchemaByIdPermanently(TestConstants.TEST_STUDY, "delete-schema");
What about when physical=true, but the caller is not an admin? (Here and deleteSchemaRevision.)

2018-08-24 23:26 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/UploadSchemaService.java
>          }
Unit test for deleting a deleted schema?

2018-08-27 17:26 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/models/upload/UploadSchemaTest.java
> +        assertTrue(jsonNode.get("deleted").booleanValue());
Yes, added

2018-08-27 17:29 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/play/controllers/UploadSchemaControllerTest.java
> +        verify(mockSvc).deleteUploadSchemaByIdPermanently(TestConstants.TEST_STUDY, "delete-schema");
Added for both forms of delete.

2018-08-27 17:35 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/UploadSchemaService.java
>          }
Added test that logically deleting logically deleted schema throws ENFE, added test that physically deleting a logically deleted schema succeeds.

2018-09-05 20:48 UTC, DwayneJengSage approved these changes

2018-09-06 16:53 UTC, merged