App config elements
Sage-Bionetworks/BridgePF pull request #1790
Opened 2018-10-19 19:44 UTC by alxdarksage

Individual JSON elements that are versioned, publishable, and accessible via the API. This covers the CRUD cases for these elements, code to include in the app config file, and to create custom editors for some fragments like medication lists, is all forthcoming.

BRIDGE-2333

2018-10-19 22:27 UTC, DwayneJengSage requested changes

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDao.java
> +    }
IndexHelper is being deprecated, because it returns results in an undefined order, and because it uses Jackson to convert between the Document API and the Mapper API, which is prone to problems if the JSON representation differs from the DDB representation (for example, for timestamps). See https://sagebionetworks.jira.com/browse/BRIDGE-1467

You can query the index directly using a mapper. For an example of how to populate all fields from the results of a GSI query, see https://github.com/Sage-Bionetworks/BridgePF/blob/develop/app/org/sagebionetworks/bridge/dynamodb/DynamoUploadSchemaDao.java#L165

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDao.java
> + */
I wouldn't recommend this. We only put keys in a GSI because additional fields means (a) more DDB storage and (b) more DDB writes. Also, we want to avoid manual bootstrap steps where possible, as this makes bootstrapping more difficult.

Instead, I'd recommend querying the index, and then re-querying the table for the rest of the fields. Reads are cheap. See my other comment for an example.

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/config/BridgeSpringConfig.java
> +    }
Would not recommend using the IndexHelper. See other comments.

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/AppConfigElementService.java
> +    }
This is unnecessary. Use DateTimeUtils.setCurrentMillisFixed() instead.

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/AppConfigElementService.java
> +        }
I would not recommend a publish workflow for this, especially not a one-way publish workflow. In practice, developers will create a revision, publish it immediately to test with, and then create a new revision, resulting in a myriad of unused revisions. This is the same reason we ended up removing the publish workflow from schemas.

It would be better to just always allow elements to be mutable.

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/AppConfigElementService.java
> +        element.setKey(studyId.getIdentifier() + ":" + element.getId());
I wouldn't recommend this. Having a separate key in the element that we have to remember to set it in every service create or update and in a bunch of DAO getters. This is error prone and could lead to bugs if we forget to do this. I'd recommend having the element itself enforce the key formatting. See for example https://github.com/Sage-Bionetworks/BridgePF/blob/develop/app/org/sagebionetworks/bridge/dynamodb/DynamoUploadSchema.java#L82

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDao.java
> +import com.newrelic.agent.deps.com.google.common.collect.Lists;
Nitpick: newrelic

(Is there anyway to exclude these from our IDE?)

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDao.java
> +                String elementKey = studyId.getIdentifier() + ":" + oneElement.getId();
Nitpick: AppConfig IDs are unique per study, so pre-pending the studyID to the hash key is unnecessary.

2018-10-19 22:27 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementTest.java
> +        assertEquals(2L, node.get("version").longValue());
Type attribute?

2018-10-19 22:27 UTC, DwayneJengSage commented on conf/routes
> +DELETE /v3/appconfigs/elements/:id/revisions/:revision         @org.sagebionetworks.bridge.play.controllers.AppConfigElementsController.deleteElementRevision(id : String, revision: String, physical:
What happens if you define revision as an Int instead of String? UploadSchema APIs currently do this.

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/play/controllers/AppConfigElementsController.java
> +        Long revision = BridgeUtils.getLongOrDefault(revisionString, 0L);
Should we be converting this to a default? Revision 0 is not a valid revision. Should we just throw in this case? Or pass it onto the service and have the service validate?

Do we need a test case for unspecified revision?

Similarly in updateElementRevision(), publishElementRevision(), and deleteElementRevision().

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/play/controllers/AppConfigElementsController.java
> +        element.setRevision(revision);
Should this logic be in the controller or the service?

2018-10-19 22:27 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/services/AppConfigElementServiceTest.java
> +        assertEquals(TIMESTAMP.getMillis(), captured.getModifiedOn());
TIMESTAMP is DateTime.now() and TestUtils creates these timestamps with DateTime.now(). We should consider using different values to ensure that the test actually works. (Similarly in updateElementRevision(), publishElementRevision(), deleteElementRevision(), deleteElementAllRevisions().)

2018-10-19 22:27 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/AppConfigElementService.java
> +        }
Do we want a test case that you can create an element with any revision?

2018-10-19 22:27 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/services/AppConfigElementServiceTest.java
> +        when(dao.getElementRevisions(TEST_STUDY, "id", false)).thenReturn(ELEMENTS);
This test modifies the app config elements in the static member ELEMENTS. If this isn't the last test that runs, this could cause weird things to happen if another test tries to use ELEMENTS. Recommend creating clean elements instead. (Similarly in deleteElementAllRevisionsPermanently().)

2018-10-19 22:27 UTC, DwayneJengSage commented
Also, how does the new AppConfig stuff interact with the old AppConfig stuff and Criteria?

2018-10-19 23:31 UTC, alxdarksage commented on conf/routes
> +DELETE /v3/appconfigs/elements/:id/revisions/:revision         @org.sagebionetworks.bridge.play.controllers.AppConfigElementsController.deleteElementRevision(id : String, revision: String, physical:
I believe if you provide a non-int, Play will return an error during parsing, which will not be our standard BadRequestException. By moving the parsing into the controller method, we get more consistent error response payloads. But I'll test this again.

2018-10-19 23:36 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/play/controllers/AppConfigElementsController.java
> +        element.setRevision(revision);
Controller, because we're enforcing the primacy of the URL over anything in the body of the message, and this is HTTP-related.

2018-10-22 19:21 UTC, alxdarksage reviewed
Updated

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/config/BridgeSpringConfig.java
> +    }
Removed.

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDao.java
> +import com.newrelic.agent.deps.com.google.common.collect.Lists;
Removed (I also Googled and found that the type filters are applied to the import support in Eclipse, so added new relic deps to this... it works.)

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDao.java
> + */
Changed to this approach, so the comment no longer true; removed. Deleted index and re-ran tests, it's created by our code and works.

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDao.java
> +    }
Changed this

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDao.java
> +                String elementKey = studyId.getIdentifier() + ":" + oneElement.getId();
The app config element key is a studyId + identifier combination. This makes it possible to use identical ids (they are user assigned) in multiple studies without a conflict.

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/play/controllers/AppConfigElementsController.java
> +        Long revision = BridgeUtils.getLongOrDefault(revisionString, 0L);
Currently would return an InvaldEntityException because the number isn't valid, but the message would be confusing. Using null, the only way you can really get an exception is if you use a non-numerical value to match the route, e.g. /v3/appconfigs/elements/:id/revisions/NOT_A_NUMBER. Switched to null, and throwing bad request exception if this method returns null.

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/AppConfigElementService.java
> +    }
Removed.

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/AppConfigElementService.java
> +        }
As I understand the schema revision system (which I based this on for consistency), you can do this, so yes, test added.

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/AppConfigElementService.java
> +        element.setKey(studyId.getIdentifier() + ":" + element.getId());
Added a setter that takes the component parts instead.

2018-10-22 19:21 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/AppConfigElementService.java
> +        }
Removed publication as discussed.

2018-10-22 19:21 UTC, alxdarksage commented on conf/routes
> +DELETE /v3/appconfigs/elements/:id/revisions/:revision         @org.sagebionetworks.bridge.play.controllers.AppConfigElementsController.deleteElementRevision(id : String, revision: String, physical:
Errors are handled not by the ExceptionInterceptor, but by a Play-specific class called the BridgeErrorHandler. Right now, it doesn't report numeric parsing errors correctly. While we could fix this, as we discussed, that's putting more code into the Play part of the system, whereas the exception interceptor is Spring-specific, centralizes our error handling, and would port to something like Spring MVC. So keeping the parsing within the controller.

2018-10-22 19:21 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementTest.java
> +        assertEquals(2L, node.get("version").longValue());
Added

2018-10-22 19:21 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/services/AppConfigElementServiceTest.java
> +        assertEquals(TIMESTAMP.getMillis(), captured.getModifiedOn());
Changed it so the values are different.

2018-10-22 19:21 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/services/AppConfigElementServiceTest.java
> +        when(dao.getElementRevisions(TEST_STUDY, "id", false)).thenReturn(ELEMENTS);
Changed this to reinitialize after every test.

2018-10-22 23:48 UTC, DwayneJengSage requested changes

2018-10-22 23:48 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElement.java
> +    }
I still wouldn't recommend this. If someone sets the studyId and Id but forgets to set the key, the app config element could get into a broken state.

Instead of having a separate key member variable and relying on callers to maintain the constraints, it would be better to not have a "key" and having the key being generated on the fly from the studyId and Id. See https://github.com/Sage-Bionetworks/BridgePF/blob/develop/app/org/sagebionetworks/bridge/dynamodb/DynamoUploadSchema.java#L82 for example.

Also, we should have unit tests that test the key is being generated correctly.

2018-10-22 23:48 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDaoTest.java
> +        assertIdAndRevision(returned.get(1), ID_2, 3L);
Test should verify the DDB query. Also, we should probably return something "real" from the DDB query and pass it into the batchLoad() to verify that the data flow is working correctly.

2018-10-22 23:48 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDaoTest.java
> +    private PaginatedQueryList<DynamoAppConfigElement> mockQueryList;
Nitpick: Is this mock being used?

2018-10-23 18:23 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElement.java
> +    }
Removed key field; added tests that it can be generated and parsed into the studyId and id

2018-10-23 18:24 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoAppConfigElementDaoTest.java
> +        assertIdAndRevision(returned.get(1), ID_2, 3L);
Verified query, verified the results returned from batchLoad are realistic for that query.

2018-10-23 23:54 UTC, DwayneJengSage approved these changes

2018-10-24 00:02 UTC, merged