Remove v3 external ID APIs
Sage-Bionetworks/BridgePF pull request #1822
Opened 2019-01-31 19:38 UTC by alxdarksage

Also switching to the use of Optional<T> instead of a boolean flag that indicates whether or not to throw an exception. The flag indicates that the caller wants to vary behavior based on presence/absence of the external identifier, and the optional object provides better idiomatic Java support to do that.

2019-02-07 01:06 UTC, DwayneJengSage requested changes

2019-02-07 01:06 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/ExternalIdService.java
> +                .orElseThrow(() -> new EntityNotFoundException(ExternalIdentifier.class));
Add unit test for missing external ID?

2019-02-07 01:06 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoExternalIdDaoTest.java
> -        externalId = dao.getExternalId(studyId, "AAA");
It would result in less code churn to write dao.getExternalId(studyId, "AAA").get();

2019-02-07 01:06 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/services/AuthenticationServiceMockTest.java
>                  .thenThrow(new EntityNotFoundException(ExternalIdentifier.class));
getExternalId() no longer throws exceptions. Should this return Optional.empty() instead?

2019-02-07 01:06 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/services/ExternalIdServiceTest.java
>      public void getExternalIdNoExtIdThrows() {
Nitpick: Rename test.

2019-02-07 22:48 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/services/ExternalIdServiceTest.java
>      public void getExternalIdNoExtIdThrows() {
Renamed

2019-02-07 22:49 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/services/AuthenticationServiceMockTest.java
>                  .thenThrow(new EntityNotFoundException(ExternalIdentifier.class));
Definitely. Changed.

2019-02-07 22:51 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoExternalIdDaoTest.java
> -        externalId = dao.getExternalId(studyId, "AAA");
Changed

2019-02-07 23:10 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/ExternalIdService.java
> +                .orElseThrow(() -> new EntityNotFoundException(ExternalIdentifier.class));
Added.

2019-02-08 00:01 UTC, DwayneJengSage approved these changes

2019-02-08 00:31 UTC, merged