Study and participant reports specific to substudies
Sage-Bionetworks/BridgePF pull request #1848
Opened 2019-04-01 22:29 UTC by alxdarksage

JIRAs:
https://sagebionetworks.jira.com/browse/BRIDGE-2392
https://sagebionetworks.jira.com/browse/BRIDGE-2394

2019-04-09 19:24 UTC, DwayneJengSage requested changes

2019-04-09 19:24 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoReportIndexDaoTest.java
>  public class DynamoReportIndexDaoTest {
It would be better to create a new class called DynamoReportIndexDaoMockTest. Otherwise, this diff is unreadable.

2019-04-09 19:24 UTC, DwayneJengSage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoReportIndexDaoTest.java
> +        verify(mapper).save(indexCaptor.capture(), eq(DynamoReportIndexDao.DOES_NOT_EXIST_EXPRESSION));
It's kind of confusing to re-use the same captor for both verifies. I would recommend using separate captors instead.

2019-04-09 19:24 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/play/controllers/ParticipantReportController.java
> +        ReportDataKey key = new ReportDataKey.Builder()
Unit tests?

2019-04-09 19:24 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/play/controllers/StudyReportController.java
> +        BridgeUtils.setRequestContext(RequestContext.NULL_INSTANCE);
Unit test?

2019-04-09 19:24 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/play/controllers/StudyReportController.java
> +        BridgeUtils.setRequestContext(RequestContext.NULL_INSTANCE);
Unit test?

2019-04-09 19:24 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/services/ReportService.java
> +        Validate.entityThrowingException(ReportDataKeyValidator.INSTANCE, key);
Unit test for updateReportIndex() validating the report?

2019-04-09 19:24 UTC, DwayneJengSage commented on app/org/sagebionetworks/bridge/validators/ReportDataValidator.java
> +            Set<String> diff = Sets.symmetricDifference(existingSubstudies, data.getSubstudyIds());
Minor: equals() works on String sets, and might be easier to read.

2019-04-10 19:46 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoReportIndexDaoTest.java
>  public class DynamoReportIndexDaoTest {
Okay, did this so DynamoReportIndexDaoxTest is a delete and DynamoReportIndexDaoMockTest is an add.

2019-04-10 19:48 UTC, alxdarksage commented on test/org/sagebionetworks/bridge/dynamodb/DynamoReportIndexDaoTest.java
> +        verify(mapper).save(indexCaptor.capture(), eq(DynamoReportIndexDao.DOES_NOT_EXIST_EXPRESSION));
Created separate captors.

2019-04-10 20:02 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/play/controllers/ParticipantReportController.java
> +        ReportDataKey key = new ReportDataKey.Builder()
Added

2019-04-10 20:08 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/play/controllers/StudyReportController.java
> +        BridgeUtils.setRequestContext(RequestContext.NULL_INSTANCE);
Added

2019-04-10 20:08 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/play/controllers/StudyReportController.java
> +        BridgeUtils.setRequestContext(RequestContext.NULL_INSTANCE);
Added

2019-04-10 20:35 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/services/ReportService.java
> +        Validate.entityThrowingException(ReportDataKeyValidator.INSTANCE, key);
Added

2019-04-10 21:27 UTC, alxdarksage commented on app/org/sagebionetworks/bridge/validators/ReportDataValidator.java
> +            Set<String> diff = Sets.symmetricDifference(existingSubstudies, data.getSubstudyIds());
Changed this to use equals. Seems obvious now that you point it out!

2019-04-11 00:42 UTC, DwayneJengSage approved these changes

2019-04-11 18:06 UTC, merged